services:
  router0:
    image: frrouting/frr
    container_name: router0
    privileged: true
    networks:
      net0-1:
        ipv4_address: 192.168.0.2

  router1:
    image: frrouting/frr
    container_name: router1
    privileged: true
    networks:
      net0-1:
        ipv4_address: 192.168.0.1
      net1-2:
        ipv4_address: 192.168.1.1
      net1-3:
        ipv4_address: 192.168.2.1

  router2:
    image: frrouting/frr
    container_name: router2
    privileged: true
    networks:
      net1-2:
        ipv4_address: 192.168.1.2
        
  router3:
    image: frrouting/frr
    container_name: router3
    privileged: true
    networks:
      net1-3:
        ipv4_address: 192.168.2.2

networks:
  net0-1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.254

  net1-2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254

  net1-3:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
